### ISSUE TITLE
Start.class not found error when launching via mcp batch file

### ISSUE THREAD

**Issue by SolDev69** [ThisTestUser/MCPFixer#11]
I found a weird issue where the launch scripts by default don't work due to Start.class not being recompiled in the right location. If anyone else has this issue I will probably leave this here as a workaround until an official fix is released if a fix is possible.
## Issue
 Start.java is in package mcp.client which is unrecognized by the launch scripts.
 
 This is the error I get-
```
== MCP 9.40 (data: 9.52, client: 1.13.2, server: 1.13.2) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
[11:52:03] Error: Could not find or load main class Start
[11:52:03] OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
'"C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot\bin\java" -Xincgc -Xms1024M -Xmx1024M -cp "..\bin\minecraft;..\src\minecraft;..\jars\versions\1.13.2\1.13.2.jar;..\lib;..\lib\*;..\jars\libraries\com\google\code\findbugs\jsr305\3.0.1\jsr305-3.0.1.jar;..\jars\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;..\jars\libraries\org\lwjgl\lwjgl-stb\3.1.6\lwjgl-stb-3.1.6.jar;..\jars\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;..\jars\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;..\jars\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;..\jars\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;..\jars\libraries\org\lwjgl\lwjgl\3.1.6\lwjgl-3.1.6-natives-windows.jar;..\jars\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;..\jars\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;..\jars\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;..\jars\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar;..\jars\libraries\com\mojang\datafixerupper\1.0.19\datafixerupper-1.0.19.jar;..\jars\libraries\com\google\guava\guava\21.0\guava-21.0.jar;..\jars\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;..\jars\libraries\org\lwjgl\lwjgl-jemalloc\3.1.6\lwjgl-jemalloc-3.1.6.jar;..\jars\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;..\jars\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;..\jars\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3-natives-windows.jar;..\jars\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;..\jars\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;..\jars\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;..\jars\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;..\jars\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;..\jars\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;..\jars\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;..\jars\libraries\org\lwjgl\lwjgl-opengl\3.1.6\lwjgl-opengl-3.1.6.jar;..\jars\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;..\jars\libraries\org\lwjgl\lwjgl-jemalloc\3.1.6\lwjgl-jemalloc-3.1.6-natives-windows.jar;..\jars\libraries\org\lwjgl\lwjgl-glfw\3.1.6\lwjgl-glfw-3.1.6.jar;..\jars\libraries\com\mojang\brigadier\1.0.14\brigadier-1.0.14.jar;..\jars\libraries\org\lwjgl\lwjgl-opengl\3.1.6\lwjgl-opengl-3.1.6-natives-windows.jar;..\jars\libraries\org\lwjgl\lwjgl\3.1.6\lwjgl-3.1.6.jar;..\jars\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;..\jars\libraries\com\mojang\realms\1.13.9\realms-1.13.9.jar;..\jars\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;..\jars\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;..\jars\libraries\org\lwjgl\lwjgl-glfw\3.1.6\lwjgl-glfw-3.1.6-natives-windows.jar;..\jars\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;..\jars\libraries\org\lwjgl\lwjgl-stb\3.1.6\lwjgl-stb-3.1.6-natives-windows.jar;..\jars\libraries\org\lwjgl\lwjgl-openal\3.1.6\lwjgl-openal-3.1.6.jar;..\jars\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;..\jars\libraries\org\lwjgl\lwjgl-openal\3.1.6\lwjgl-openal-3.1.6-natives-windows.jar;..\jars\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar" -Djava.library.path=..\jars\versions\1.13.2\1.13.2-natives Start' failed : 1
FATAL ERROR
Traceback (most recent call last):
  File "runtime\startclient.py", line 43, in startclient
  File "C:\Users\user\Downloads\mcp952\runtime\commands.py", line 1678, in startclient
    self.runmc(forkcmd)
  File "C:\Users\user\Downloads\mcp952\runtime\commands.py", line 1718, in runmc
    raise CalledProcessError(process.returncode, forkcmd, output)
CalledProcessError: Command '"C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot\bin\java" -Xincgc -Xms1024M -Xmx1024M -cp "..\bin\minecraft;..\src\minecraft;..\jars\versions\1.13.2\1.13.2.jar;..\lib;..\lib\*;..\jars\libraries\com\google\code\findbugs\jsr305\3.0.1\jsr305-3.0.1.jar;..\jars\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;..\jars\libraries\org\lwjgl\lwjgl-stb\3.1.6\lwjgl-stb-3.1.6.jar;..\jars\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;..\jars\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;..\jars\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;..\jars\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;..\jars\libraries\org\lwjgl\lwjgl\3.1.6\lwjgl-3.1.6-natives-windows.jar;..\jars\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;..\jars\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;..\jars\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;..\jars\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar;..\jars\libraries\com\mojang\datafixerupper\1.0.19\datafixerupper-1.0.19.jar;..\jars\libraries\com\google\guava\guava\21.0\guava-21.0.jar;..\jars\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;..\jars\libraries\org\lwjgl\lwjgl-jemalloc\3.1.6\lwjgl-jemalloc-3.1.6.jar;..\jars\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;..\jars\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;..\jars\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3-natives-windows.jar;..\jars\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;..\jars\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;..\jars\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;..\jars\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;..\jars\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;..\jars\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;..\jars\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;..\jars\libraries\org\lwjgl\lwjgl-opengl\3.1.6\lwjgl-opengl-3.1.6.jar;..\jars\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;..\jars\libraries\org\lwjgl\lwjgl-jemalloc\3.1.6\lwjgl-jemalloc-3.1.6-natives-windows.jar;..\jars\libraries\org\lwjgl\lwjgl-glfw\3.1.6\lwjgl-glfw-3.1.6.jar;..\jars\libraries\com\mojang\brigadier\1.0.14\brigadier-1.0.14.jar;..\jars\libraries\org\lwjgl\lwjgl-opengl\3.1.6\lwjgl-opengl-3.1.6-natives-windows.jar;..\jars\libraries\org\lwjgl\lwjgl\3.1.6\lwjgl-3.1.6.jar;..\jars\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;..\jars\libraries\com\mojang\realms\1.13.9\realms-1.13.9.jar;..\jars\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;..\jars\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;..\jars\libraries\org\lwjgl\lwjgl-glfw\3.1.6\lwjgl-glfw-3.1.6-natives-windows.jar;..\jars\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;..\jars\libraries\org\lwjgl\lwjgl-stb\3.1.6\lwjgl-stb-3.1.6-natives-windows.jar;..\jars\libraries\org\lwjgl\lwjgl-openal\3.1.6\lwjgl-openal-3.1.6.jar;..\jars\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;..\jars\libraries\org\lwjgl\lwjgl-openal\3.1.6\lwjgl-openal-3.1.6-natives-windows.jar;..\jars\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar" -Djava.library.path=..\jars\versions\1.13.2\1.13.2-natives Start' returned non-zero exit status 1
Press any key to continue . . .
```

## Fix
Remove a single line of code, `package mcp.client` from Start.java before recompiling and launching.
## Versions affected
From my testing, 1.15.2 and 1.13.2, but most versions except 1.12.2 are probably affected in some way.

**Comment by ThisTestUser** [comment]
~~I don't remember having this issue, but then again I always launch via the IDE, so I may have manually fixed it before launching. Either way this seems to be a minor issue so there won't be an automatic fix for it.~~

Update: I'll fix this in the next release of the Fixer program.
