### ISSUE TITLE
Cannot start decompiled MC. Dependence issue

### ISSUE THREAD

**Issue by jLynx** [ThisTestUser/MCPFixer#3]
Please close if this is too far off the topic.

So I have decompiled 1.13. I have set it up in IntelliJ.
I have then fixed the dependencies so that they are all found.
The issue I am having is when I try run, it attempts to start but then crashing with the following error:

```
"A:\Program Files\Java\jdk1.8.0_101\bin\java" -Djava.library.path=versions\1.13\1.13-natives -Didea.launcher.port=7538 "-Didea.launcher.bin.path=A:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.2\bin" -Dfile.encoding=UTF-8 -classpath "{{A BUNCH OF STUFF NOT RELEVANT TO THIS ERROR}}A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\mcp940\jars\libraries\org\lwjgl\lwjgl-glfw\3.1.6\lwjgl-glfw-3.1.6.jar;A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\mcp940\jars\libraries\org\lwjgl\lwjgl-stb\3.1.6\lwjgl-stb-3.1.6.jar;A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\mcp940\jars\libraries\org\lwjgl\lwjgl-openal\3.1.6\lwjgl-openal-3.1.6.jar;A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\mcp940\jars\libraries\org\lwjgl\lwjgl\3.1.6\lwjgl-3.1.6.jar;A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\mcp940\jars\libraries\org\lwjgl\lwjgl-opengl\3.1.6\lwjgl-opengl-3.1.6.jar;A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\mcp940\jars\libraries\org\lwjgl\lwjgl\3.1.6\lwjgl-3.1.6-natives-windows.jar;A:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.2\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain mcp.client.Start
[09:20:12] [Client thread/INFO]: Setting user: Player125
[09:20:14] [Client thread/INFO]: LWJGL Version: 3.1.6 build 14
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/07/19 9:20 AM
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL
	at net.minecraft.client.MainWindow.throwExceptionForGlError(MainWindow.java:226)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1649)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1827)
	at net.minecraft.client.MainWindow.<init>(MainWindow.java:91)
	at net.minecraft.client.renderer.VirtualScreen.createMainWindow(VirtualScreen.java:103)
	at net.minecraft.client.Minecraft.init(Minecraft.java:502)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at mcp.client.Start.main(Start.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.MainWindow.throwExceptionForGlError(MainWindow.java:226)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1649)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1827)
	at net.minecraft.client.MainWindow.<init>(MainWindow.java:91)
	at net.minecraft.client.renderer.VirtualScreen.createMainWindow(VirtualScreen.java:103)
	at net.minecraft.client.Minecraft.init(Minecraft.java:502)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:129)
	at mcp.client.Start.main(Start.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

-- System Details --
Details:
	Minecraft Version: 1.13
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141613024 bytes (135 MB) / 279445504 bytes (266 MB) up to 3808428032 bytes (3632 MB)
	JVM Flags: 0 total; 
	Launched Version: mcp
	LWJGL: 3.1.6 build 14
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\mcp940\jars\.\crash-reports\crash-2019-07-03_09.20.14-client.txt

Process finished with exit code -1
```

So its something to do with dependencies I assume, Do you know what I need to add or change to get this to run?

Thanks!
![image](https://user-images.githubusercontent.com/4393979/60548626-a4513d00-9d76-11e9-9b86-e3a728191deb.png)
![image](https://user-images.githubusercontent.com/4393979/60548644-af0bd200-9d76-11e9-8b6b-1ed4251c9409.png)

Edit:
When I change around some of the dependences I can get this error:
```
[09:45:41] [Client thread/INFO]: Setting user: Player848
[09:45:42] [Client thread/INFO]: LWJGL Version: 3.1.6 build 14
[09:45:42] [Client thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[09:45:42] [Client thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[09:45:42] [Client thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
```

**Comment by jLynx** [comment]
Basically, if I add ```lwjgl-3.1.6-natives-windows.jar``` I get the error:
```java.lang.IllegalStateException: GLFW error 65542: WGL: The driver does not appear to support OpenGL```

If i remove it, i get the error
```[STDERR]: [LWJGL] Failed to load a library.```

**Comment by ThisTestUser** [comment]
This has to do with the build path being preset by MCP, so you'll always have to update them.
Did you add 1.13-natives from jars/versions to 1.13.jar?

**Comment by jLynx** [comment]
Is this what you mean by that?
![image](https://user-images.githubusercontent.com/4393979/60550823-64da1f00-9d7d-11e9-8c82-09e685294e08.png)

(Sorry for my ignorance)

**Comment by jLynx** [comment]
Also my 1.13-natives folder only contains dll's
![image](https://user-images.githubusercontent.com/4393979/60550946-bc788a80-9d7d-11e9-87e8-221273833434.png)

**Comment by ThisTestUser** [comment]
![NativeLib](https://user-images.githubusercontent.com/15678918/60550995-dbccd480-9cf7-11e9-8c2a-0830c14d53bf.PNG)

**Comment by ThisTestUser** [comment]
You're using IntelliJ, I don't know how you would do that, but this is what you would do in Eclipse.

**Comment by jLynx** [comment]
I'll just give this a shot in eclipse to see if I can get it working there with your setup

**Comment by jLynx** [comment]
Ah I worked out how to add the natives 
![image](https://user-images.githubusercontent.com/4393979/60551674-27c35c00-9d80-11e9-9bb7-24514d47e3ea.png)

Still not working though 
(Still installing eclipse)

**Comment by ThisTestUser** [comment]
Did you add all the libraries then?
And if it still doesn't work, try launching 1.13.2 regularly via your minecraft launcher.
I was able to make it work after adding all the libraries and setting the natives.

**Comment by jLynx** [comment]
Found the issue... Wont work over RDP(No graphics drivers). When I connected via TeamViewer it worked ("Ish") still a few lib issues to iron out. Will close this issue in a few if I can get it launched 

Ahh, the joys of remote development

**Comment by jLynx** [comment]
All working now, Thanks for the amazing help you have given me!
