### ISSUE TITLE
Lost Textures and other things (1.13.2)

### ISSUE THREAD

**Issue by reply7251** [ThisTestUser/MCPFixer#6]
I use the way and the tool you provide and I found that something error.
Before decompiled the MCP, I found that there wasn't a Start.java in conf/patches and inject folder.
So, I copy them from origin MCP folder then I can decompile it.
When I trying to Run Client, it start success with icon and background.
But on the Main Menu all font are just rectangles, the world's texture are lost.
Some textures not lost are like items(blocks) added in 1.13 and entities.
I don't know how to solve it.

![2019-11-08_13 46 41](https://user-images.githubusercontent.com/24792782/68453113-a00ac400-022f-11ea-84b3-7a5402a0cea3.png)
![2019-11-08_13 46 50](https://user-images.githubusercontent.com/24792782/68453114-a00ac400-022f-11ea-95aa-78c7ae6ad517.png)

There is my log:
> [13:45:45] [Client thread/INFO]: Setting user: Player655
[13:45:47] [Client thread/WARN]: Skipping bad option: lastServer:
[13:45:47] [Client thread/INFO]: LWJGL Version: 3.1.6 build 14
[13:45:48] [Client thread/INFO]: Reloading ResourceManager: Default
[13:45:48] [Client thread/WARN]: Missing sound for event: minecraft:ambient.cave
[13:45:48] [Client thread/WARN]: Missing sound for event: minecraft:ambient.underwater.enter
... ...
[13:45:48] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:45:49] [Thread-2/INFO]: Initializing No Sound
[13:45:49] [Thread-2/INFO]: (Silent Mode)
[13:45:49] [Thread-2/INFO]: OpenAL initialized.
[13:45:49] [Sound Library Loader/INFO]: Sound engine started
[13:45:50] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/block/oak_door_top.png : java.io.FileNotFoundException: minecraft:textures/block/oak_door_top.png
[13:45:50] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/block/tnt_bottom.png : java.io.FileNotFoundException: minecraft:textures/block/tnt_bottom.png
... ...
[13:45:58] [Server thread/INFO]: Preparing spawn area: 4%
... ...
java.lang.IllegalArgumentException: Data fixer not registered for: minecraft:DUMMY in block_entity
	at com.mojang.datafixers.schemas.Schema.getChoiceType(Schema.java:107) ~[datafixerupper-1.0.19.jar:?]
	at net.minecraft.util.datafix.NamespacedSchema.getChoiceType(NamespacedSchema.java:23) ~[bin/:?]
	at net.minecraft.util.datafix.fixes.NamedEntityFix.makeRule(NamedEntityFix.java:27) ~[bin/:?]
	at com.mojang.datafixers.DataFix.getRule(DataFix.java:97) ~[datafixerupper-1.0.19.jar:?]
	at com.mojang.datafixers.DataFixerUpper.getRule(DataFixerUpper.java:135) ~[datafixerupper-1.0.19.jar:?]
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:83) ~[datafixerupper-1.0.19.jar:?]
	at net.minecraft.nbt.NBTUtil.update(NBTUtil.java:345) ~[bin/:?]
	at net.minecraft.nbt.NBTUtil.update(NBTUtil.java:340) ~[bin/:?]
	at net.minecraft.world.gen.feature.template.TemplateManager.loadTemplate(TemplateManager.java:168) ~[bin/:?]
	at net.minecraft.world.gen.feature.template.TemplateManager.loadTemplateResource(TemplateManager.java:82) ~[bin/:?]
	at net.minecraft.world.gen.feature.template.TemplateManager.lambda$0(TemplateManager.java:66) ~[bin/:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) [?:1.8.0_201]
	at net.minecraft.world.gen.feature.template.TemplateManager.getTemplate(TemplateManager.java:63) [bin/:?]
	at net.minecraft.world.gen.feature.template.TemplateManager.getTemplateDefaulted(TemplateManager.java:49) [bin/:?]
	at net.minecraft.world.gen.feature.structure.ShipwreckPieces$Piece.func_204754_a(ShipwreckPieces.java:77) [bin/:?]
	at net.minecraft.world.gen.feature.structure.ShipwreckPieces$Piece.readAdditional(ShipwreckPieces.java:72) [bin/:?]
	at net.minecraft.world.gen.feature.structure.StructurePiece.read(StructurePiece.java:95) [bin/:?]
	at net.minecraft.world.gen.feature.structure.StructureIO.getStructureComponent(StructureIO.java:102) [bin/:?]
	at net.minecraft.world.gen.feature.structure.StructureStart.read(StructureStart.java:139) [bin/:?]
	at net.minecraft.world.gen.feature.structure.StructureIO.func_202602_a(StructureIO.java:70) [bin/:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.readStructureStartsFromNBT(AnvilChunkLoader.java:915) [bin/:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.readChunkFromNBT(AnvilChunkLoader.java:662) [bin/:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT(AnvilChunkLoader.java:228) [bin/:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk(AnvilChunkLoader.java:154) [bin/:?]
	at net.minecraft.world.gen.ChunkProviderServer.getChunk(ChunkProviderServer.java:124) [bin/:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunks(ChunkProviderServer.java:174) [bin/:?]
	at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:485) [bin/:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:90) [bin/:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:106) [bin/:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:699) [bin/:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
... ...

**Comment by reply7251** [comment]
I found that you use method move to move the Start,jar, so I can only use the Fixer once.
When I try again, it will be no Start.jar

**Comment by ghost** [comment]
What do you mean 'method move?' I'm having the exact same problem, what did you do?
